Resolving small mistakes
Evil-Bees/Alertit pull request #26
Opened 2023-01-13 17:33 UTC by macck7

resolving all the mistakes specified by @cehicm

2023-01-13 18:35 UTC, cehicm requested changes
Please fix the following changes, also, as I previously mentioned, the commit message doesn't communicate what's going on the commit. If anyone else looks at it, they won't know what the commit does. Feel free to separate the changes into several commits, for example:
- Update Alertit.js variable name
- Update XY component styles, etc

2023-01-13 18:35 UTC, cehicm commented on components/Alert.js
> -      <div style={{ height : '50px' }}>
As I mentioned in the previous message, `height` needs to be replaced with a [Tailwind ](https://tailwindcss.com/docs/height )class, deleting it is not the solution.

2023-01-13 18:35 UTC, cehicm commented on src/components/signin-cta.js
> -						{/* <span className="block py-2 mt-5 bg-indigo-700 text-center mix-blend-multiply">
There were two parts of this text, so we still needed this span. Again, deleting it is not the correct way to go about it. Please add it back.

2023-01-13 18:35 UTC, cehicm commented on pages/register.js
> +				<SignInCTA sample_text="Ready to take your monitoring to the next level? Sign up to take control of your sites and devices - all from
In NextJS (and React and JavaScript for that matter) the convention is to use camel case, so it would be `sampleText`, but again, this name isn't quite descriptive, please take a look at [this part of the Contributing guidelines](https://github.com/Evil-Bees/Alertit/blob/main/CONTRIBUTING.md#naming-conventions).

2023-01-13 18:35 UTC, cehicm commented on components/Alert.js
> +        const alert  = text.toLowerCase();
Again, it's not clear what this function (or variable) stand for, please write a more descriptive name. Check out the [Contributing guide](https://github.com/Evil-Bees/Alertit/blob/main/CONTRIBUTING.md) please

2023-01-14 16:40 UTC, macck7 commented
@cehicm I have resolved bot issuse  in two different commit.

2023-01-14 16:50 UTC, macck7 commented
previously in status page, when someone write invalid id then it pop up a alert...
i have added a custom alert, which auomatically closes after 2 sec..

2023-01-14 17:40 UTC, cehicm approved these changes
Good work, thanks!

2023-01-14 18:12 UTC, cehicm commented on pages/status/index.js
> +      props.showAlert("Please enter valid ID", "danger")
"Danger" is not necessary, we don't want the users to be alarmed by this message, please delete.

2023-01-15 15:00 UTC, macck7 commented on pages/status/index.js
> +      props.showAlert("Please enter valid ID", "danger")
@cehicm  Done !!!

2023-01-16 21:42 UTC, cehicm approved these changes

2023-01-16 21:43 UTC, nikolap994 commented on README.md
> +      <td align="center"><a href="https://github.com/macck7"><img src="https://avatars.githubusercontent.com/u/49000628?s=400&u=88fb08d9546d72d92ddc0eaa4da1822497dfd65e&v=4" width="100px;" alt="Mohit
I actually removed this section. It's problematic when there is large number of contributors, so I decided to remove it and we will post them later on the our site (evilbees.com). Ones with most contributors will be displayed there as a thanks 😄

2023-01-16 22:50 UTC, cehicm commented
Looks good, please resolve the conflicts so we can merge these changes @macck7  :)

2023-01-17 21:59 UTC, merged

2023-01-17 21:59 UTC, nikolap994 commented
The PR is merged. No need for any action. 😄 
For future reference please make commits smaller and make sure you always pull from main branch before making PR.